### PR TITLE
feat: static files are available to tests

### LINKED ISSUE #247: preset-karma: static folder serve: true
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

If you want to serve files in your Karma tests you'll have to set up file-serving yourself.

```
  presets: [
    require('poi-preset-karma')({
      files: [
        'test/*.test.js',
        {pattern: 'test/*.m??', watched: false, included: false, served: true, nocache: false},
      ]
    })
  ],
```

In my particular test case I'm fetching an audio file for the server for processing. 

**What is the expected behavior?**

`static` folder is already treated in a special way. E.g. webpack automatically copies the files in static folder.

It would be convenient if the karma preset would also serve these when running tests.

```
     {pattern: 'static/*', watched: false, included: false, served: true, nocache: false},
```

(maybe `nocache` should be true, I'm undecided on that one)

**If this is a feature request, what is motivation or use case for changing the behavior?**

Delightful web development for Front-End (and testing)

ps: I can work on a PR if it makes sense to you to have this feature

### PR DESCRIPTION
**Pull request by mblarsen**
Useful for when your tests uses XHR to fetch files from a server.

Normally files that are served through Karma is mapped to (in the case
of static):

    /base/static/example.mp3

But I've set up a proxy so they become available through:

   /static/example.mp3

I think this is the most intuitive mapping.

Closes #247

### CODE REVIEW

**Comment by mblarsen** [comment]
Hmm, do you (@egoist) map static folder otherwise to the root like:

```
/example.mp3
```
or 

```
/static/example.mp3
```

I should probably use the same. Easier to grasp.

**Comment by egoist** [comment]
yeah it should be `/example.mp3` in this case, we serve it at root pathl

**Comment by mblarsen** [comment]
Hmm, it might present a problem. At least you'll get a warning.  https://github.com/karma-runner/karma/blob/master/lib/config.js#L178

```
06 10 2017 22:34:14.563:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
```

Although there could by conflicts I don't think that there practically would be. Then you could override.

**Comment by mblarsen** [comment]
Anyway, I updated it to be included at root.

**Pull request merged**
