### PR TITLE
feat(html-entry): enable external resources in dev mode

### LINKED ISSUE #570: [html-entry] Don't strip external resources in development mode
At the moment Poi strips all external script resources from the HTML template while in dev mode:

https://github.com/egoist/poi/blob/e7cd5c2010f51f5000e71ea25668eb287fc8d49b/plugins/html-entry/lib/html-entry-loader.js#L42-L53

Is it possible to change this behavior and return the unprocessed `node`? IMO most users will want external resources to be available during development.

For example: I have integrated `netlify-cms` in my app, but cant use it in dev mode, because both of this scripts are removed:

```html
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
```

### PR DESCRIPTION
**Pull request by r0skar**
fix #570

### CODE REVIEW

**Comment by egoist** [comment]
Don't return the node if it should be processed by webpack

**Comment by r0skar** [comment]
Sorry, but I am not 100% sure what you mean. Wasn't that the old behavior as well? Returning the node after processing its `src` attribute?

**Comment by egoist** [comment]
hmm I can't merge it locally because you deleted the repo.

**Comment by r0skar** [comment]
Yeah sorry about that. I have cleaned up some repositories and have removed it by mistake.

**Comment by egoist** [comment]
shipped in `poi@12.6.9`

**Pull request closed without merging**
