### PR TITLE
Add https option

### LINKED ISSUE #195: Add option to create HTTPS development server
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

**What is the current behavior?**
There's no support for secure dev servers (HTTPS).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To be able to use an HTTPS server.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm currently using a secure localhost server to develop features, because my development assets need to load on a HTTPS page.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
I can make a PR. There's code for self-signed certificates in [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/v2.5.0/lib/Server.js#L355-L410), so it would be basically copy&paste.

### PR DESCRIPTION
**Pull request by skyrpex**
Fixes #195.

### CODE REVIEW

**Comment by skyrpex** [comment]
Maybe we could move the secure server code in `bin/run.js` to `lib/create-server-listener.js`

**Comment by egoist** [comment]
Also, maybe we can try to switch to webpack-dev-server 😅

**Comment by skyrpex** [comment]
That may be easier to maintain :stuck_out_tongue:

**Comment by egoist** [comment]
So I'm closing this now, thanks for your work anyways!

**Pull request closed without merging**
