### PR TITLE
Support multi-compiler

### PR DESCRIPTION
**Pull request by qqcome110**
Support multi-compiler from issue #237 

When the `poi dev` command encounters multiple compilers, there are two solutions

* Solution A:

If there are more than one compiler, this PR will take the 1st one as the processing object

* Solution B:

If there are more than one compiler, this PR will terminate and prompt the error message to the user

**Now this PR apply Solution A**
I don't know how to deal with the more appropriate, please give a feedback

### CODE REVIEW

**Comment by egoist** [comment]
In which case the `compiler` would be a MultiCompiler?

**Comment by qqcome110** [comment]
Yeah! If not this PR will do nothing

**Comment by egoist** [comment]
so why do we need this PR? `this.compiler` always only contains a single compiler

**Comment by qqcome110** [comment]
As issue #241 When webpack config is return a multi configs

**Comment by egoist** [comment]
@qqcome110 Ah I see

**Comment by egoist** [comment]
Hmm, 

> If there are more than one compiler, this PR will take the 1st one as the processing object

So why do you return an array of webpack configs in `webpack(config) {}` in the first place?

**Comment by qqcome110** [comment]
When you run `poi dev` will do this, But `poi build` & `poi watch` will be not

**Comment by egoist** [comment]
they actually should have consistent behavior IMO.

**Comment by qqcome110** [comment]
You mean that they are all return 1st one compiler?

**Comment by egoist** [comment]
I don't get it, why do you return multi webpack config and only use the first one.

**Comment by qqcome110** [comment]
I think you didn't understand what I meant

**Comment by qqcome110** [comment]
When you encounter multiple compilers, `poi dev` will get 1st one compiler, and the other commands will normally return multiple, You can see more about [multi-compiler](https://github.com/webpack/webpack/tree/master/examples/multi-compiler) of the official example

**Comment by qqcome110** [comment]
And "poi dev" do not have to use this solution, As above solutions, you can give the user wrong message, They are need to make a decision

**Comment by qqcome110** [comment]
I get your mean, If return multi webpack config can weigh whether to support multiple servers

**Comment by qqcome110** [comment]
https://github.com/webpack/webpack/issues/1849
https://github.com/webpack/webpack-dev-middleware/pull/151

**Comment by allenfantasy** [comment]
IMO the main problem of this issue would be: currently Poi could not support multi compiler. And the PR just solve this problem, but we need to confirm:

> how Poi should deal with multiple compilers in `dev` mode

And since webpack-dev-server has already support a multiple compiler config (see the comment [here](https://github.com/webpack/webpack-dev-server/issues/641#issuecomment-325338039) which points out that [this PR](https://github.com/webpack/webpack-dev-middleware/pull/187) has solved the problems), IMO we should **create multiple webpack-dev-server instances** but I haven't got time to verify this theory. 

cc @qqcome110

**Comment by allenfantasy** [comment]
Any ideas about this PR? @egoist

**Pull request closed without merging**
