### PR TITLE
Ignore ".gitkeep" in static folder.

### PR DESCRIPTION
**Pull request by gluons**
Avoid copying `.gitkeep` from static folder.

### CODE REVIEW

**Comment by egoist** [comment]
Any other dotfiles we can always ignore? if yes we can include them in this PR too 😄

**Comment by mblarsen** [comment]
Well since you have `.gitkeep`, `.gitignore` is an obvious choice :P

**Comment by egoist** [comment]
@mblarsen but you will never put `.gitignore` inside `static` 😄

**Comment by mblarsen** [comment]
@egoist yes, many people use `.gitignore` interchangeable with `.gitkeep`

**Comment by gluons** [comment]
Maybe

**Windows:**
- `Thumbs.db`
- `Desktop.ini`

**Linux:**
- `.directory` (KDE directory preferences)

**Pull request merged**
