### PR TITLE
remove all console.* calls, when minimizing

### PR DESCRIPTION
**Pull request by Boorj**
added `drop_console : true` in Terser plugin options

### CODE REVIEW

**Comment by egoist** [comment]
hmm I think sometimes yo do need `console.log` in production?

**Comment by Boorj** [comment]
@egoist sure, but shouldn't be there an option to remove that? i can't find any minification customization. Is there any?

**Comment by egoist** [comment]
You can modify the options for Terser plugin using the `chainWebpack` option:

```js
module.exports = {
  chainWebpack(config) {
    if (config.plugins.has('minimize')) {
      config.plugin('minimize').tap(([options]) => {
        options.terserOptions.compress.drop_console = true
        return [options]
      })
    }
  }
}
```

**Comment by Boorj** [comment]
Thanks for `tap`! i used this code 
```js
config.plugin('minimize').get('args')[0].terserOptions.compress.drop_console = true;
```
But your code seems to be proper.

**Comment by Boorj** [comment]
@egoist How do you think, could this option for minification be used in in next versions of poi?

**Pull request closed without merging**
